version: '3'
services:
  eva-ics:
    container_name: eva_basic_1
    hostname: eva_1
    environment:
      - auto_install=1
      - mqtt=
      - link=1
      - product=all
      - layout=enterprise
      - MASTERKEY=demo123
      - DEFAULTKEY=
      - OPKEY=
      - OPPASSWD=123
      - cloud_manager=1
      - deploy=
      - download=
      - debug=
    image: altertech/eva-ics
    volumes:
        - ui:/mnt/ui
        - pvt:/mnt/pvt
        - backup:/mnt/backup
        - runtime:/mnt/runtime
        - log:/mnt/log
    networks:
      ic:
        ipv4_address: 10.27.5.10

networks:
  ic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.27.5.0/24

volumes:
  ui:
  pvt:
  backup:
  runtime:
  log:
